// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_loginapi_index from "./routes/api/loginapi/index.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logindos from "./routes/logindos.tsx";
import * as $register from "./routes/register.tsx";
import * as $rick_id_ from "./routes/rick/[id].tsx";
import * as $video_id_ from "./routes/video/[id].tsx";
import * as $videos from "./routes/videos.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Favourites from "./islands/Favourites.tsx";
import * as $LoginIsland from "./islands/LoginIsland.tsx";
import * as $LogoutButton from "./islands/LogoutButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/loginapi/index.ts": $api_loginapi_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logindos.tsx": $logindos,
    "./routes/register.tsx": $register,
    "./routes/rick/[id].tsx": $rick_id_,
    "./routes/video/[id].tsx": $video_id_,
    "./routes/videos.tsx": $videos,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Favourites.tsx": $Favourites,
    "./islands/LoginIsland.tsx": $LoginIsland,
    "./islands/LogoutButton.tsx": $LogoutButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
